name: Release package to Git

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack ./src/Serilog.Enrichers.Kubernetes.sln --configuration Release /p:Version=${VERSION} --output .
    - name: Push to github
      run: dotnet nuget push Serilog.Enrichers.Kubernetes.${VERSION}.nupkg --source https://nuget.pkg.github.com/vanwinkelseppe/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      